@startuml
actor "Admin" as fc
actor "Client"as cli
usecase "Vehicle" as UC1
usecase "Order" as order
usecase "Booking" as booking
usecase "Insurance" as insurance
usecase "Payment" as payment
fc --> UC1 : Gère
cli --> UC1 : Consulte & réserve
cli --> order : Créer
booking --> order : Inclu
insurance --> booking : Peu être incluse
payment --> order : Inclus 
@enduml
