@startuml
entity "Client" {
* id
* firstname
* lastname
* email
* password
* licenceIssueDate
}

entity "Booking" {
* id
* startDate
* endDate
* vehicleId
}

entity "Order" {
* id
* status
* payment
}

entity "Payment" {
* id
* amount
}

entity "Insurance" {
* id
* name
* price
}

Client ||--o{ Booking : "has many"
Booking ||--|| Order : "has one"
Order ||--|| Payment : "has one"
Booking }o--|| Insurance : "can have many"
@enduml